[package]
name = "simula_core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
enum-iterator = "0.7.0"
enum-display-derive = "0.1.1"

[dev-dependencies]
