[package]
name = "simula_viz"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy.git", version = "0.6", features = ["dynamic"] }

[lib]
path = "lib.rs"